# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: Yayın Kontrolü

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
  schedule:
    - cron: 00 00 * * *
  push:
    paths:
      - KONTROL.py
      - .github/workflows/Kontrol.yml
      - Kanallar/KekikAkademi.m3u

jobs:
  YayinKontrol:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write
      issues  : write

    steps:
      - name : Depo Kontrolü
        uses : actions/checkout@v4

      - name : Python 3.11.8 Yükle
        uses : actions/setup-python@v5
        with :
          python-version: 3.11.8

      - name : Python Sürümünü Göster
        run  : python -c "import sys; print(sys.version)"

      - name : Gereksinimleri Yükle
        run  : |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik cloudscraper jq

      - name : Betiği Çalıştır
        run  : |
          python KONTROL.py

      - name : Değişiklik Kontrolü
        id   : degisiklik_kontrol
        run  : |
          if [ -f HATALAR.md ]; then
            echo "degisiklik=true" >> $GITHUB_OUTPUT
          fi

      - name : Mevcut Issue'ları Kontrol Et ve Kapat
        if   : steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run  : |
          existing_issue=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            | jq -r '.[] | select(.title == "⚠️ Kontrol Edilmesi Gereken Linkler") | .number')

          if [ -n "$existing_issue" ]; then
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$existing_issue \
              -d '{"state":"closed"}'
          fi

      - name : Issue Aç
        if   : steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run  : |
          hatalar=$(cat HATALAR.md)
          body=$(echo "$hatalar" | jq -sR .)
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"⚠️ Kontrol Edilmesi Gereken Linkler","body":'"$body"',"labels":["help wanted"]}'
